PIPELINE_NAME: BiteScore
ARTIFACTS_DIR : Artifacts
TARGET_COLUMN : Rating
SCHEMA_PATH : schema.yaml

file_locations : 
  Raw:
    input : Data/Raw/zomato.csv
    output : Data/Processed/zomato.csv

  mapping:
    restaurant_type : Data/Mapping/restaurant_type_mapping.json
    cuisine : Data/Mapping/cuisine_group_mapping.json
    location : Data/Mapping/location_mapping.json

  Formatted:
    Train : Data/Formatted/train.csv
    Test : Data/Formatted/test.csv
    Validation : Data/Formatted/val.csv

Database_Details:
  Database_Name : BiteScore
  Train_Collection : Train
  Test_Collection : Test
  Validation_Collection : Validation