preprocess : 
  input : Data/Raw/zomato.csv
  mapping:
    restaurant_type : Data/Mapping/restaurant_type_mapping.json
    cuisine : Data/Mapping/cuisine_group_mapping.json
    location : Data/Mapping/location_mapping.json
  output : Data/Processed/zomato.csv